import { FormikProvider, useFormik } from "formik";
import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import tw from "twin.macro";
import loginCheckpoint from "@/api/auth/loginCheckpoint";
import LoginFormContainer from "@/components/auth/LoginFormContainer";
import Button from "@/components/elements/Button";
import Field from "@/components/elements/Field";
import useFlash from "@/plugins/useFlash";

interface Values {
	code: string;
	recoveryCode: string;
}

export default () => {
	const navigate = useNavigate();
	const location = useLocation();
	const { clearAndAddHttpError } = useFlash();
	const [isMissingDevice, setIsMissingDevice] = useState(false);

	const token = (location.state as { token?: string })?.token;

	const formik = useFormik<Values>({
		initialValues: {
			code: "",
			recoveryCode: "",
		},
		onSubmit: ({ code, recoveryCode }, { setSubmitting }) => {
			if (!token) return;
			loginCheckpoint(token, code, recoveryCode)
				.then((response) => {
					if (response.complete) {
						// @ts-expect-error this is valid
						window.location = response.intended || "/";
						return;
					}
					setSubmitting(false);
				})
				.catch((error) => {
					console.error(error);
					setSubmitting(false);
					clearAndAddHttpError({ error });
				});
		},
	});

	if (!token) {
		navigate("/auth/login", { replace: true });
		return null;
	}

	return (
		<LoginFormContainer title={"Device Checkpoint"} css={tw`w-full flex`}>
			<FormikProvider value={formik}>
				<form onSubmit={formik.handleSubmit}>
					<div css={tw`mt-6`}>
						<Field
							light
							name={isMissingDevice ? "recoveryCode" : "code"}
							title={isMissingDevice ? "Recovery Code" : "Authentication Code"}
							description={
								isMissingDevice
									? "Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue."
									: "Enter the two-factor token generated by your device."
							}
							type={"text"}
							autoComplete={"one-time-code"}
							autoFocus
						/>
					</div>
					<div css={tw`mt-6`}>
						<Button
							size={"xlarge"}
							type={"submit"}
							disabled={formik.isSubmitting}
							isLoading={formik.isSubmitting}
						>
							Continue
						</Button>
					</div>
					<div css={tw`mt-6 text-center`}>
						<span
							onClick={() => {
								formik.setFieldValue("code", "");
								formik.setFieldValue("recoveryCode", "");
								setIsMissingDevice((s) => !s);
							}}
							css={tw`cursor-pointer text-xs text-neutral-500 tracking-wide uppercase no-underline hover:text-neutral-700`}
						>
							{!isMissingDevice ? "I've Lost My Device" : "I Have My Device"}
						</span>
					</div>
					<div css={tw`mt-6 text-center`}>
						<Link
							to={"/auth/login"}
							css={tw`text-xs text-neutral-500 tracking-wide uppercase no-underline hover:text-neutral-700`}
						>
							Return to Login
						</Link>
					</div>
				</form>
			</FormikProvider>
		</LoginFormContainer>
	);
};
