import { useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useLocation, useNavigate } from "react-router-dom";
import tw from "twin.macro";
import loginCheckpoint from "@/api/auth/loginCheckpoint";
import LoginFormContainer from "@/components/auth/LoginFormContainer";
import Button from "@/components/elements/Button";
import FormField from "@/components/elements/FormField";
import useFlash from "@/plugins/useFlash";

interface Values {
	code: string;
	recoveryCode: string;
}

export default () => {
	const navigate = useNavigate();
	const location = useLocation();
	const { clearAndAddHttpError } = useFlash();
	const [isMissingDevice, setIsMissingDevice] = useState(false);

	const token = (location.state as { token?: string })?.token;

	const {
		register,
		handleSubmit,
		formState: { isSubmitting },
		setValue,
	} = useForm<Values>({
		defaultValues: {
			code: "",
			recoveryCode: "",
		},
	});

	const onSubmit = ({ code, recoveryCode }: Values) => {
		if (!token) return;
		loginCheckpoint(token, code, recoveryCode)
			.then((response) => {
				if (response.complete) {
					// @ts-expect-error this is valid
					window.location = response.intended || "/";
					return;
				}
			})
			.catch((error) => {
				console.error(error);
				clearAndAddHttpError({ error });
			});
	};

	if (!token) {
		navigate("/auth/login", { replace: true });
		return null;
	}

	return (
		<LoginFormContainer title={"Device Checkpoint"} css={tw`w-full flex`}>
			<form onSubmit={handleSubmit(onSubmit)}>
				<div css={tw`mt-6`}>
					<FormField
						light
						id={isMissingDevice ? "recoveryCode" : "code"}
						label={isMissingDevice ? "Recovery Code" : "Authentication Code"}
						description={
							isMissingDevice
								? "Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue."
								: "Enter the two-factor token generated by your device."
						}
						type={"text"}
						autoComplete={"one-time-code"}
						autoFocus
						{...register(isMissingDevice ? "recoveryCode" : "code")}
					/>
				</div>
				<div css={tw`mt-6`}>
					<Button
						size={"xlarge"}
						type={"submit"}
						disabled={isSubmitting}
						isLoading={isSubmitting}
					>
						Continue
					</Button>
				</div>
				<div css={tw`mt-6 text-center`}>
					<span
						onClick={() => {
							setValue("code", "");
							setValue("recoveryCode", "");
							setIsMissingDevice((s) => !s);
						}}
						css={tw`cursor-pointer text-xs text-neutral-500 tracking-wide uppercase no-underline hover:text-neutral-700`}
					>
						{!isMissingDevice ? "I've Lost My Device" : "I Have My Device"}
					</span>
				</div>
				<div css={tw`mt-6 text-center`}>
					<Link
						to={"/auth/login"}
						css={tw`text-xs text-neutral-500 tracking-wide uppercase no-underline hover:text-neutral-700`}
					>
						Return to Login
					</Link>
				</div>
			</form>
		</LoginFormContainer>
	);
};
