name: Pre-Discussed and Approved Topics
description: For topics already previously discussed and approved in the GitHub Discussions section.
body:
  - type: markdown
    attributes:
      value: |
        **DO NOT** open a new issue for feature requests _without prior maintainer approval_ and corresponding
        thread in the discussions section. You MUST link to the corresponding discussion thread when opening
        this feature request issue or it will be closed without further consideration.
  - type: textarea
    attributes:
      label: The Feature Request
  - type: input
    attributes:
      label: GitHub Discussion Link
      description: Link to the GitHub Discussions thread where the feature was previously discussed and approved.
    validations:
      required: true
