name: Release
on:
  push:
    branches:
      - "**"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile
      - run: bun run type-check
      - run: bun run lint
      - run: bun run test

      - name: Build & Package DEVELOPMENT
        run: |
          mkdir -p target
          bun run package:dev
          mv panel.tar.gz target/panel-dev.tar.gz

      - name: Build & Package DEVELOPMENT-HASHED-COMPRESS
        run: |
          bun run package:dev-hash-compress
          mv panel.tar.gz target/panel-dev-hash-compress.tar.gz

      - name: Build & Package PRODUCTION-COMPRESS-BROTLI-SPLIT
        run: |
          bun run package:prod-compress-brotli-split
          mv panel.tar.gz target/panel-prod-compress-brotli-split.tar.gz
          cp target/panel-prod-compress-brotli-split.tar.gz target/panel.tar.gz

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Automated Build"
          files: |
            target/panel-dev.tar.gz
            target/panel-dev-hash-compress.tar.gz
            target/panel-prod-compress-brotli-split.tar.gz
